# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build levinson nice nano'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["levinson_left","levinson_right"]'
